#version 450

struct inst {
  vec4 rot;
  vec4 pos;  // pos.xyz + mdl
  vec4 size; // size.xyz + txt
};
struct obj {
  vec4 pos; // pos.xyz + hit
};

layout(binding = 0, set = 0) readonly buffer buf_0 { inst inp[]; };
layout(binding = 0, set = 1) buffer buf_1 { obj obp[]; };

void main() {
  uint ii = gl_GlobalInvocationID.x;
  uint oi = gl_GlobalInvocationID.y;

  uint in_mdl = uint(inp[ii].pos.w);
  switch (in_mdl) {
    case 2:
      obp[oi].pos.w = 99;
      break;
  }
}
